[package]
name = "bevy_spectator"
description = "A spectator camera plugin for Bevy"
version = "0.2.0"
edition = "2021"
authors = ["JonahPlusPlus <33059163+JonahPlusPlus@users.noreply.github.com>"]
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/bevy_spectator"
homepage = "https://github.com/JonahPlusPlus/bevy_spectator"
repository = "https://github.com/JonahPlusPlus/bevy_spectator"
exclude = ["/examples/"]

[dependencies]
bevy = { version = "0.11.0", default-features = false }

[dev-dependencies]
bevy = "0.11.0"

[features]
default = ["init"]
init = [] # enables automatically choosing a camera

[[example]]
name = "basic"
path = "examples/basic.rs"

[[example]]
name = "3d_scene"
path = "examples/3d_scene.rs"
